[package]
name = "lisp_rs"
version = "0.1.0"
authors = ["hehaowen00"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.8.1"
rustyline = "5.0.4"